config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'posts#index'

  get 'posts/index'
  get 'shelters/index'
  get 'dogs/index'
  
  resources :posts
  resources :shelters
  resources :dogs

end

app/models/dog.rb
class Dog < ActiveRecord::Base
    belongs_to :shelter
    has_one :post
    mount_uploader :d_image, DogImageUploader
end

app/models/post.rb
class Post < ActiveRecord::Base
    belongs_to :user
end

app/models/shelter.rb
class Shelter < ActiveRecord::Base
    has_many :dogs
    mount_uploader :s_image, ShelterImageUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
  mount_uploader :avatar, AvatarUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :nickname])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :nickname])
  end
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  def index
    @dogs = Dog.all.order('created_at asc')
    @shelters = Shelter.all.order('created_at asc')
  end
  
  def new
    @shelters = Shelter.all.order('created_at asc')
  end 

  def create
    new_dog = Dog.new(d_name: params[:d_name], age: params[:age], sex: params[:sex], 
                      weight: params[:weight], species: params[:species], unusual: params[:unusual],
                      d_day: params[:d_day], shelter_id: params[:shelter_id], d_image: params[:d_image])
    if new_dog.save
      redirect_to dogs_index_path
    else
      redirect_to new_dog_path
    end
  end
  
  def edit
    @dog = Dog.find_by(id: params[:id])
    @shelters = Shelter.all.order('created_at asc')
  end
  
  def update
    @dog = Dog.find_by(id: params[:id])
    redirect_to shelter_path(params[:shelter_id]) if User.find_by(email:"admin@gmail.com").id != current_user.id
    
    @dog.d_name = params[:d_name]
    @dog.age = params[:age]
    @dog.sex = params[:sex]
    @dog.weight = params[:weight]
    @dog.species = params[:species]
    @dog.unusual = params[:unusual]
    @dog.d_day = params[:d_day]
    @dog.shelter_id = params[:shelter_id]
    # @dog.d_image = params[:d_image] if params[:d_image].present?
    @dog.d_image = params[:d_image]
    
    if @dog.save
      redirect_to shelter_path(params[:shelter_id])
    else
      render :edit
    end
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  end
end

app/controllers/shelters_controller.rb
class SheltersController < ApplicationController
  before_action :authenticate_user!
 
  def index
  end
  
  def index
    @shelters = Shelter.all.order('created_at asc')
  end
  
  def new
  end
  
  def create
    new_shelter = Shelter.new(s_name: params[:s_name],s_location: params[:s_location],s_phone: params[:s_phone], s_image: params[:s_image])
    
    if new_shelter.save
      redirect_to shelters_index_path
    else
      redirect_to new_shelter_path
    end
    
  end
  
  def show
    @shelter = Shelter.find_by(id: params[:id])
    @Dogs = Dog.where(shelter_id: params[:id])
  
  end
  
  def edit
    @shelter = Shelter.find_by(id: params[:id])
  end
  
  def update
    @shelter = Shelter.find_by(id: params[:id])
    redirect_to shelter_index_path(params[:shelter_id]) if User.find_by(email:"admin@gmail.com").id != current_user.id
    
    @shelter.s_name = params[:s_name]
    @shelter.s_location = params[:s_location]
    @shelter.s_phone = params[:s_phone]
    # @shelter.s_image = params[:s_image] if params[:s_image].present?
    @shelter.s_image = params[:s_image]
    
    if @shelter.save
      redirect_to shelter_index_path(params[:id])
    else
      render :edit
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/shelters_helper.rb
module SheltersHelper
end

app/views/dogs/edit.html.erb
        <div class="container"> 
            <div class="row"> 
                <div class="card col s12"> 
                    <div class="card-content"> 
                        <div class="card-title">강아지 수정하기</div> 
                        <%= form_tag dog_path(@dog), method: "patch", multipart: true do %> 
                            
                            <input type="hidden" name="id" value="<%=@dog.id%>">
                            <!--update액션에서 파라미터로 받아올 수 있음-->
                            
                             <label>보호소 선택</label>
                             <!--원래 선택되어있던 보호소가 선택될 수 있도록 수정-->
                              <select class="browser-default" name="shelter_id">
                                <option value="" disabled selected>보호소를 선택해주세요</option>
                                    <% @shelters.each do |shelter| %>
                                      <% if @dog.shelter_id == shelter.id %>
                                      <option value="<%= shelter.id %>" selected="selected"><%= shelter.s_name %></option>
                                      <% else %>
                                      <option value="<%= shelter.id %>"><%= shelter.s_name %></option>
                                      <% end %>
                                    <% end %>
                              </select>
                        
                            <div class="input-field"> 
                            <%= text_area_tag :d_name, @dog.d_name, class: "materialize-textarea", placeholder: "강아지 이름 작성" %> 
                            </div>
                            
                            <div class="input-field"> 
                            <%= text_area_tag :age, @dog.age, class: "materialize-textarea", placeholder: "강아지 나이 작성(숫자만 작성)" %> 
                            </div>
                            
                            <% if @dog.sex == "male"%>
                            <p>
                              <input name="sex" type="radio" id="male" value="male" checked="checked"/>
                              <label for="male">남자</label>
                            </p>
                            <p>
                              <input name="sex" type="radio" id="female" value="female"/>
                              <label for="female">여자</label>
                            </p>
                            <% else %>
                            <p>
                              <input name="sex" type="radio" id="male" value="male"/>
                              <label for="male">남자</label>
                            </p>
                            <p>
                              <input name="sex" type="radio" id="female" value="female" checked="checked"/>
                              <label for="female">여자</label>
                            </p>
                            <% end %>
                            
                            <div class="input-field"> 
                            <%= text_area_tag :weight, @dog.weight, class: "materialize-textarea", placeholder: "강아지 몸무게 작성(숫자만 작성)" %> 
                            </div>
                            
                            <div class="input-field"> 
                            <%= text_area_tag :species, @dog.species, class: "materialize-textarea", placeholder: "강아지 종류 작성" %> 
                            </div>
                            
                            <div class="input-field"> 
                            <%= text_area_tag :unusual, @dog.unusual, class: "materialize-textarea", placeholder: "특이사항 작성" %> 
                            </div>
                            
                            <label>안락사 날짜</label>
                            <input type="text" class="datepicker" name="d_day" value = <%= @dog.d_day %>>
                                
                            <label>강아지 사진</label>    
                            <div class="input-field"> 
                                <%= file_field_tag :d_image %> 
                            </div>

                            <div class="input-field"> 
                            <%= button_tag "수정하기", class: "btn" %> 
                            </div> 
                        <% end %> 
                    </div> 
                </div> 
            </div> 
        </div>

app/views/dogs/index.html.erb
<div class="container">
    <div class="row">
          <% @dogs.each do |dog| %>
              <div class="col cyan lighten-4">
                  <center>
                    <% if dog.d_image.url %>
                      <img src="<%= dog.d_image.url %>" /></br>
                    <% end %>
                    <%= dog.d_name%></br>
                    <%= dog.sex%></br>
                    <%= dog.age%>살</br>
                    <%= dog.weight%>kg</br>
                    <%= dog.shelter_id%></br>
                    <%= dog.species%></br>
                    <%= dog.unusual%></br>
                    <%= dog.d_day%></br>
                  </center>
              </div>
              <% if current_user.email == "admin@gmail.com" %>
                <%= link_to "수정", edit_dog_path(dog.id), class: "right" %>
              <% end %>
          <% end %>      
    </div>
</div>

app/views/dogs/new.html.erb
        <div class="container"> 
            <div class="row"> 
                <div class="card col s12"> 
                    <div class="card-content"> 
                        <div class="card-title">강아지 추가하기</div> 
                        <%= form_tag dogs_path do %> 
                             
                             <label>보호소 선택</label>
                              <select class="browser-default" name="shelter_id">
                                <option value="" disabled selected>보호소를 선택해주세요</option>
                                    <% @shelters.each do |shelter| %>
                                      <option value="<%= shelter.id %>"><%= shelter.s_name %></option>
                                    <% end %>
                              </select>
                        
                            <div class="input-field"> 
                            <%= text_area_tag :d_name, nil, class: "materialize-textarea", placeholder: "강아지 이름 작성" %> 
                            </div>
                            
                            <div class="input-field"> 
                            <%= text_area_tag :age, nil, class: "materialize-textarea", placeholder: "강아지 나이 작성(숫자만 작성)" %> 
                            </div>
                            
                            <p>
                              <input name="sex" type="radio" id="male" value="male"/>
                              <label for="male">남자</label>
                            </p>
                            <p>
                              <input name="sex" type="radio" id="female" value="female"/>
                              <label for="female">여자</label>
                            </p>
                            
                            <div class="input-field"> 
                            <%= text_area_tag :weight, nil, class: "materialize-textarea", placeholder: "강아지 몸무게 작성(숫자만 작성)" %> 
                            </div>
                            
                            <div class="input-field"> 
                            <%= text_area_tag :species, nil, class: "materialize-textarea", placeholder: "강아지 종류 작성" %> 
                            </div>
                            
                            <div class="input-field"> 
                            <%= text_area_tag :unusual, nil, class: "materialize-textarea", placeholder: "특이사항 작성" %> 
                            </div>
                            
                            <label>안락사 날짜</label>
                            <input type="text" class="datepicker" name="d_day">
                                
                            <label>강아지 사진</label>    
                            <div class="input-field"> 
                                <%= file_field_tag :d_image %> 
                            </div>

                            <div class="input-field"> 
                            <%= button_tag "작성하기", class: "btn" %> 
                            </div> 
                        <% end %> 
                    </div> 
                </div> 
            </div> 
        </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  
  <title>LET PET</title>
   <!--Import Google Icon Font-->
      <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
      
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  
  <!--Let browser know website is optimized for mobile-->
      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
      
</head>
<body>

  <ul class="right">
    <% if user_signed_in? %>
      <li><%= current_user.name + " 님"%></li>
      <li><%= link_to 'Sign out', destroy_user_session_path, method: 'delete' %></li>
      <li><a href="/shelters/new">보호소 추가</a></li>
      <li><a href="/dogs/new">강아지 추가</a></li>
    <% else %>  
      <li><a href="/users/sign_in">로그인</li>
      <li><a href="/users/sign_up">회원가입</a></li>
    <% end %>  
    
  </ul>


<div class = "logo">
<center>
  <a href="/"><img src ="../assets/logo.png" width="20%" ></a>
</center> 

</div>

<%= yield %>



<!--dy : top 버튼-->

<img class = "topbtn" img src = "../assets/topbtn.png" align="right">

<script>
    <!--위로올라가기-->
    $( window ).scroll( function() {
	    if ( $( this ).scrollTop() > 100 ) {
	        $( '.topbtn' ).fadeIn();
	    }
	    else {
	        $( '.topbtn' ).fadeOut();
	    }
	} );
	
    $( '.topbtn' ).click( function() {
	    $( 'html, body' ).animate( { scrollTop : 0 }, 400 );
	    return false;
	} );
	
// 	materialize 옵션 선택
    $(document).ready(function() {
    $('select').material_select();
  });
     
  // 데이트 픽커   
  $('.datepicker').pickadate({
    selectMonths: true, // Creates a dropdown to control month
    selectYears: 15, // Creates a dropdown of 15 years to control year,
    today: 'Today',
    clear: 'Clear',
    close: 'Ok',
    closeOnSelect: false, // Close upon selecting a date
    format: 'yyyy,mm,dd',
    formatSubmit: 'yyyy,mm,dd'
  });
  
</script>

</body>



 <!--dy: 카피라이터 & 푸터-->
<footer>
  <div class = "copyright">
  <p>Copyright 2017. LETPET All rights reserved.</p>
  </div>
</footer>
</html>

app/views/posts/index.html.erb
<header>
  
  <meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">


 
<div class = nav>
  
        <center>
          <a href="/shelters/index">유기견 보호소</a> |
          <a href="#">가족을 찾습니다</a>  
      </center>
</div>



<body>
    
    
    




<div class="mainbanner">
<center><img src="../assets/dog.jpg" style="width:100%"></center> 
</div>


<div class="drawsvg">
    <svg version="1.1" viewBox="0 0 1000 400">
      <symbol id="fade-text">
        <text x="50%" y="100%" text-anchor="middle" name="title">당신의 따뜻한 손길을 기다립니다 </text>
      </symbol>
      
      <g>
        <use class="stroke" xlink:href="#fade-text"/>
        <use class="fill" xlink:href="#fade-text"/>
      </g>
    </svg>					
</div>

<br>
   


 <div class="container">
    <center>
    <div class = "flex">
        
    <div class="col-3 ">
        <img src="../assets/example.PNG" style="width:60%;">
    <p id="title"><%= link_to '내용' %></p>
        
       
    </div>

    <div class="col-3">
        <img src="../assets/example.PNG" style="width:60%;" >
  <p id="title"><%= link_to '내용' %></p>
    </div>
    
    <div class="col-3 ">
        <img src="../assets/example.PNG" style="width:60%;" >
  <p id="title"><%= link_to '내용' %></p>
    </div>
        
    <div class="col-3 ">
       <img src="../assets/example.PNG" style="width:60%;" >
     <p id="title"><%= link_to '내용' %></p>
    </div>
        
        
    </div>
    
      </center>
    </div>    



<div class="w3-content w3-display-container" style="max-width:800px">
  <img class="mySlides" src="../assets/dog.jpg" style="width:100%">
  <img class="mySlides" src="../assets/dog.jpg" style="width:100%">
  <img class="mySlides" src="../assets/dog.jpg" style="width:100%">
  <div class="w3-center w3-container w3-section w3-large w3-text-white w3-display-bottommiddle" style="width:100%">
    <div class="w3-left w3-hover-text-khaki" onclick="plusDivs(-1)">&#10094;</div>
    <div class="w3-right w3-hover-text-khaki" onclick="plusDivs(1)">&#10095;</div>
    <span class="w3-badge demo w3-border w3-transparent w3-hover-white" onclick="currentDiv(1)"></span>
    <span class="w3-badge demo w3-border w3-transparent w3-hover-white" onclick="currentDiv(2)"></span>
    <span class="w3-badge demo w3-border w3-transparent w3-hover-white" onclick="currentDiv(3)"></span>
  </div>
</div>

<script>
var slideIndex = 1;
showDivs(slideIndex);

function plusDivs(n) {
  showDivs(slideIndex += n);
}

function currentDiv(n) {
  showDivs(slideIndex = n);
}

function showDivs(n) {
  var i;
  var x = document.getElementsByClassName("mySlides");
  var dots = document.getElementsByClassName("demo");
  if (n > x.length) {slideIndex = 1}
  if (n < 1) {slideIndex = x.length}
  for (i = 0; i < x.length; i++) {
     x[i].style.display = "none";
  }
  for (i = 0; i < dots.length; i++) {
     dots[i].className = dots[i].className.replace(" w3-white", "");
  }
  x[slideIndex-1].style.display = "block";
  dots[slideIndex-1].className += " w3-white";
}
</script>
   
   
      
    
    
    

  
</body>

app/views/shelters/edit.html.erb
<div class="container"> 
    <div class="row"> 
        <div class="card col s12"> 
            <div class="card-content"> 
                <div class="card-title">보호소 수정하기</div> 
                <%= form_tag shelter_path(@shelter), method: "patch", multipart: true do %> 
                    <input type="hidden" name="id" value="<%= @shelter.id %>">
                    
                    <div class="input-field"> 
                    <%= text_area_tag :s_name, @shelter.s_name, class: "materialize-textarea", placeholder: "보호소 이름 작성" %> 
                    </div>
                    
                    <div class="input-field"> 
                    <%= text_area_tag :s_location, @shelter.s_location, class: "materialize-textarea", placeholder: "보호소 위치 작성" %> 
                    </div>
                    
                    <div class="input-field"> 
                    <%= text_area_tag :s_phone, @shelter.s_phone, class: "materialize-textarea", placeholder: "보호소 전화번호 작성 ex) 02-0000-0000" %> 
                    </div>
                    
                    <label>보호소 사진</label>
                    <div class="input-field"> 
                        <%= file_field_tag :s_image %> 
                    </div>

                    
                    <div class="input-field"> 
                    <%= button_tag "수정하기", class: "btn" %> 
                    </div> 
                <% end %> 
            </div> 
        </div> 
    </div> 
</div>

app/views/shelters/index.html.erb
<div class="container">
    <div class="row">
          <% @shelters.each do |shelter| %>
                <div class="col cyan lighten-4" style="cursor:pointer" onclick="location.href='/shelters/<%= shelter.id %>';">
                  <center>
                    <% if shelter.s_image.url %>
                      <img src="<%= shelter.s_image.url %>" />
                    <% end %>
                    <%= shelter.s_name%><br/>
                    <%= shelter.s_location%>
                  </center>
                  <% if current_user.email == "admin@gmail.com" %>
                    <%= link_to "수정", edit_shelter_path(shelter.id), class: "right" %>
                  <% end %>
                </div>
          <% end %>      
    </div>
</div>

app/views/shelters/new.html.erb
<div class="container"> 
    <div class="row"> 
        <div class="card col s12"> 
            <div class="card-content"> 
                <div class="card-title">보호소 작성하기</div> 
                <%= form_tag shelters_path do %> 
                    <div class="input-field"> 
                    <%= text_area_tag :s_name, nil, class: "materialize-textarea", placeholder: "보호소 이름 작성" %> 
                    </div>
                    
                    <div class="input-field"> 
                    <%= text_area_tag :s_location, nil, class: "materialize-textarea", placeholder: "보호소 위치 작성" %> 
                    </div>
                    
                    <div class="input-field"> 
                    <%= text_area_tag :s_phone, nil, class: "materialize-textarea", placeholder: "보호소 전화번호 작성 ex) 02-0000-0000" %> 
                    </div>
                    
                    <label>보호소 사진</label>
                    <div class="input-field"> 
                        <%= file_field_tag :s_image %> 
                    </div>

                    
                    <div class="input-field"> 
                    <%= button_tag "작성하기", class: "btn" %> 
                    </div> 
                <% end %> 
            </div> 
        </div> 
    </div> 
</div>

app/views/shelters/show.html.erb
<div class="container">
    <% if @shelter.s_image.url %>
        <img src="<%= @shelter.s_image.url %>" />
    <% end %>
    <%= @shelter.s_name %></br>
    <%= @shelter.s_location %>
</div>

<div class="container">
    <div class="row">
          <% @Dogs.each do |dog| %>
              <div class="col cyan lighten-4">
                  <center>
                    <% if dog.d_image.url %>
                      <img src="<%= dog.d_image.url %>"/></br>
                    <% end %>
                    <%= dog.d_name%></br>
                    <%= dog.sex%></br>
                    <%= dog.age%>살</br>
                    <%= dog.weight%>kg</br>
                    <%= dog.species%></br>
                    <%= dog.unusual%></br>
                    <%= dog.d_day%></br>
                  </center>
                  <% if current_user.email == "admin@gmail.com" %>
                    <%= link_to "수정", edit_dog_path(dog.id), class: "right" %>
                  <% end %>
              </div>
          <% end %>      
    </div>
</div>